CREATE TABLE programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_code VARCHAR(50) NOT NULL,
    program_name VARCHAR(255) NOT NULL,
    degree_level VARCHAR(100) NOT NULL,
    department_id BIGINT NOT NULL,
    duration_years INTEGER,
    total_credits INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_programs_program_code UNIQUE (program_code),
    CONSTRAINT uk_programs_department_name_degree
        UNIQUE (department_id, program_name, degree_level),
    CONSTRAINT fk_programs_department
        FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_programs_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_programs_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id),
    CONSTRAINT chk_programs_duration_years
        CHECK (duration_years IS NULL OR duration_years > 0),
    CONSTRAINT chk_programs_total_credits
        CHECK (total_credits IS NULL OR total_credits > 0)
);

CREATE INDEX idx_programs_department_id ON programs (department_id);
CREATE INDEX idx_programs_degree_level ON programs (degree_level);
CREATE INDEX idx_programs_is_active ON programs (is_active);
CREATE INDEX idx_programs_is_deleted ON programs (is_deleted);
CREATE INDEX idx_programs_created_by ON programs (created_by);
CREATE INDEX idx_programs_updated_by ON programs (updated_by);
CREATE INDEX idx_programs_department_active_deleted ON programs (department_id, is_active, is_deleted);
