CREATE TABLE semesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_name_th VARCHAR(150) NOT NULL,
    semester_name_en VARCHAR(150) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_semesters_name_th_en
        UNIQUE (semester_name_th, semester_name_en),
    CONSTRAINT fk_semesters_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_semesters_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_semesters_is_deleted ON semesters (is_deleted);
CREATE INDEX idx_semesters_created_by ON semesters (created_by);
CREATE INDEX idx_semesters_updated_by ON semesters (updated_by);
