CREATE TABLE lectures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecture_name_th VARCHAR(255) NOT NULL,
    lecture_name_en VARCHAR(255) NOT NULL,
    lecture_nickname VARCHAR(100),
    faculty_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_lectures_department_names
        UNIQUE (department_id, lecture_name_th, lecture_name_en),
    CONSTRAINT chk_lectures_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT fk_lectures_faculty
        FOREIGN KEY (faculty_id) REFERENCES faculties(id),
    CONSTRAINT fk_lectures_department
        FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_lectures_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_lectures_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_lectures_faculty_id ON lectures (faculty_id);
CREATE INDEX idx_lectures_department_id ON lectures (department_id);
CREATE INDEX idx_lectures_status ON lectures (status);
CREATE INDEX idx_lectures_is_deleted ON lectures (is_deleted);
CREATE INDEX idx_lectures_created_by ON lectures (created_by);
CREATE INDEX idx_lectures_updated_by ON lectures (updated_by);
CREATE INDEX idx_lectures_department_status_deleted
    ON lectures (department_id, status, is_deleted);
