CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(50) NOT NULL,
    course_name VARCHAR(255) NOT NULL,
    credit_hours INTEGER NOT NULL,
    description VARCHAR(1000),
    faculty_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    program_id BIGINT,
    semester_id BIGINT,
    recommended_academic_year SMALLINT,
    prerequisite_courses VARCHAR(1000),
    course_type SMALLINT NOT NULL,
    maximum_students_per_section INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_courses_course_code UNIQUE (course_code),
    CONSTRAINT chk_courses_credit_hours CHECK (credit_hours > 0),
    CONSTRAINT chk_courses_recommended_academic_year
        CHECK (recommended_academic_year IS NULL OR recommended_academic_year > 0),
    CONSTRAINT chk_courses_course_type CHECK (course_type IN (100, 200, 300)),
    CONSTRAINT chk_courses_maximum_students
        CHECK (maximum_students_per_section IS NULL OR maximum_students_per_section > 0),
    CONSTRAINT fk_courses_faculty
        FOREIGN KEY (faculty_id) REFERENCES faculties(id),
    CONSTRAINT fk_courses_department
        FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_courses_program
        FOREIGN KEY (program_id) REFERENCES programs(id),
    CONSTRAINT fk_courses_semester
        FOREIGN KEY (semester_id) REFERENCES semesters(id),
    CONSTRAINT fk_courses_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_courses_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_courses_faculty_id ON courses (faculty_id);
CREATE INDEX idx_courses_department_id ON courses (department_id);
CREATE INDEX idx_courses_program_id ON courses (program_id);
CREATE INDEX idx_courses_semester_id ON courses (semester_id);
CREATE INDEX idx_courses_course_type ON courses (course_type);
CREATE INDEX idx_courses_is_active ON courses (is_active);
CREATE INDEX idx_courses_is_deleted ON courses (is_deleted);
CREATE INDEX idx_courses_created_by ON courses (created_by);
CREATE INDEX idx_courses_updated_by ON courses (updated_by);
CREATE INDEX idx_courses_academic_filters
    ON courses (faculty_id, department_id, program_id, semester_id, is_active, is_deleted);
