CREATE TABLE course_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    section_number VARCHAR(20) NOT NULL,
    capacity INTEGER NOT NULL,
    lecture_id BIGINT NOT NULL,
    room VARCHAR(100),
    schedule VARCHAR(255),
    semester_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_course_sections_course_section_semester
        UNIQUE (course_id, section_number, semester_id),
    CONSTRAINT chk_course_sections_capacity
        CHECK (capacity > 0),
    CONSTRAINT chk_course_sections_status
        CHECK (status IN ('ACTIVE', 'CLOSED')),
    CONSTRAINT fk_course_sections_course
        FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_course_sections_lecture
        FOREIGN KEY (lecture_id) REFERENCES lectures(id),
    CONSTRAINT fk_course_sections_semester
        FOREIGN KEY (semester_id) REFERENCES semesters(id),
    CONSTRAINT fk_course_sections_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_course_sections_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_course_sections_course_id ON course_sections (course_id);
CREATE INDEX idx_course_sections_lecture_id ON course_sections (lecture_id);
CREATE INDEX idx_course_sections_semester_id ON course_sections (semester_id);
CREATE INDEX idx_course_sections_status ON course_sections (status);
CREATE INDEX idx_course_sections_is_deleted ON course_sections (is_deleted);
CREATE INDEX idx_course_sections_created_by ON course_sections (created_by);
CREATE INDEX idx_course_sections_updated_by ON course_sections (updated_by);
CREATE INDEX idx_course_sections_semester_status_deleted
    ON course_sections (semester_id, status, is_deleted);
