CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR(50) NOT NULL,
    university_email VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(30),
    date_of_birth DATE,
    faculty_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    semester_id BIGINT,
    academic_year SMALLINT,
    enrollment_year SMALLINT,
    account_status VARCHAR(30) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_students_student_code UNIQUE (student_code),
    CONSTRAINT uk_students_university_email UNIQUE (university_email),
    CONSTRAINT chk_students_academic_year
        CHECK (academic_year IS NULL OR academic_year BETWEEN 1900 AND 9999),
    CONSTRAINT chk_students_enrollment_year
        CHECK (enrollment_year IS NULL OR enrollment_year BETWEEN 1900 AND 9999),
    CONSTRAINT chk_students_account_status
        CHECK (account_status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED')),
    CONSTRAINT fk_students_faculty
        FOREIGN KEY (faculty_id) REFERENCES faculties(id),
    CONSTRAINT fk_students_department
        FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_students_program
        FOREIGN KEY (program_id) REFERENCES programs(id),
    CONSTRAINT fk_students_semester
        FOREIGN KEY (semester_id) REFERENCES semesters(id),
    CONSTRAINT fk_students_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_students_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_students_faculty_id ON students (faculty_id);
CREATE INDEX idx_students_department_id ON students (department_id);
CREATE INDEX idx_students_program_id ON students (program_id);
CREATE INDEX idx_students_semester_id ON students (semester_id);
CREATE INDEX idx_students_academic_year ON students (academic_year);
CREATE INDEX idx_students_enrollment_year ON students (enrollment_year);
CREATE INDEX idx_students_account_status ON students (account_status);
CREATE INDEX idx_students_is_deleted ON students (is_deleted);
CREATE INDEX idx_students_created_by ON students (created_by);
CREATE INDEX idx_students_updated_by ON students (updated_by);
CREATE INDEX idx_students_academic_filters
    ON students (faculty_id, department_id, program_id, semester_id,
                 academic_year, account_status, is_deleted);
