CREATE TABLE student_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    force_password_change BOOLEAN NOT NULL DEFAULT FALSE,
    password_changed_at TIMESTAMP,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT uk_student_credentials_student_id UNIQUE (student_id),
    CONSTRAINT chk_student_credentials_failed_attempts
        CHECK (failed_login_attempts >= 0),
    CONSTRAINT fk_student_credentials_student
        FOREIGN KEY (student_id) REFERENCES students(id)
);
