CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_section_id BIGINT NOT NULL,
    enrollment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(30) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_enrollments_student_course_section
        UNIQUE (student_id, course_section_id),
    CONSTRAINT chk_enrollments_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'WITHDRAWN', 'DROPPED')),
    CONSTRAINT fk_enrollments_student
        FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_enrollments_course_section
        FOREIGN KEY (course_section_id) REFERENCES course_sections(id),
    CONSTRAINT fk_enrollments_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_enrollments_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_enrollments_student_id ON enrollments (student_id);
CREATE INDEX idx_enrollments_course_section_id ON enrollments (course_section_id);
CREATE INDEX idx_enrollments_enrollment_date ON enrollments (enrollment_date);
CREATE INDEX idx_enrollments_status ON enrollments (status);
CREATE INDEX idx_enrollments_is_deleted ON enrollments (is_deleted);
CREATE INDEX idx_enrollments_created_by ON enrollments (created_by);
CREATE INDEX idx_enrollments_updated_by ON enrollments (updated_by);
CREATE INDEX idx_enrollments_section_status_deleted
    ON enrollments (course_section_id, status, is_deleted);
CREATE INDEX idx_enrollments_student_status_deleted
    ON enrollments (student_id, status, is_deleted);
