CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(30),
    department_id BIGINT,
    account_status VARCHAR(30) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_app_users_employee_id UNIQUE (employee_id),
    CONSTRAINT uk_app_users_email UNIQUE (email),
    CONSTRAINT fk_app_users_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_app_users_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_app_users_department_id ON app_users (department_id);
CREATE INDEX idx_app_users_created_by ON app_users (created_by);
CREATE INDEX idx_app_users_updated_by ON app_users (updated_by);
