CREATE TABLE app_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by BIGINT,

    CONSTRAINT fk_app_user_roles_user
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_app_user_roles_role
        FOREIGN KEY (role_id) REFERENCES app_roles(id),
    CONSTRAINT fk_app_user_roles_assigned_by
        FOREIGN KEY (assigned_by) REFERENCES app_users(id),
    CONSTRAINT uk_app_user_roles_user_role UNIQUE (user_id, role_id)
);

CREATE INDEX idx_app_user_roles_role_id ON app_user_roles (role_id);
CREATE INDEX idx_app_user_roles_assigned_by ON app_user_roles (assigned_by);
