CREATE TABLE appuser_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    force_password_change BOOLEAN NOT NULL DEFAULT TRUE,
    password_changed_at TIMESTAMP,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT uk_appuser_credentials_user UNIQUE (user_id),
    CONSTRAINT fk_appuser_credentials_user
        FOREIGN KEY (user_id) REFERENCES app_users(id)
);
