CREATE TABLE faculties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_code VARCHAR(30) NOT NULL,
    faculty_name_en VARCHAR(255) NOT NULL,
    faculty_name_th VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_faculties_faculty_code UNIQUE (faculty_code),
    CONSTRAINT uk_faculties_faculty_name_en UNIQUE (faculty_name_en),
    CONSTRAINT fk_faculties_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_faculties_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_faculties_is_active ON faculties (is_active);
CREATE INDEX idx_faculties_is_deleted ON faculties (is_deleted);
CREATE INDEX idx_faculties_created_by ON faculties (created_by);
CREATE INDEX idx_faculties_updated_by ON faculties (updated_by);
