CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code VARCHAR(30) NOT NULL,
    department_name VARCHAR(255) NOT NULL,
    faculty_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT uk_departments_department_code UNIQUE (department_code),
    CONSTRAINT uk_departments_faculty_department_name UNIQUE (faculty_id, department_name),
    CONSTRAINT fk_departments_faculty
        FOREIGN KEY (faculty_id) REFERENCES faculties(id),
    CONSTRAINT fk_departments_created_by
        FOREIGN KEY (created_by) REFERENCES app_users(id),
    CONSTRAINT fk_departments_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users(id)
);

CREATE INDEX idx_departments_faculty_id ON departments (faculty_id);
CREATE INDEX idx_departments_is_active ON departments (is_active);
CREATE INDEX idx_departments_is_deleted ON departments (is_deleted);
CREATE INDEX idx_departments_created_by ON departments (created_by);
CREATE INDEX idx_departments_updated_by ON departments (updated_by);
CREATE INDEX idx_departments_faculty_active_deleted ON departments (faculty_id, is_active, is_deleted);
